version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    platform: linux/amd64
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - db:/var/lib/mysql


volumes: 
  db:      

