version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    platform: linux/amd64
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=wizeq_password
      - MYSQL_DATABASE=wizeq
      - MYSQL_TCP_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  integration-tests-prisma:
    image: mysql:8.0
    container_name: integration-tests-prisma
    platform: linux/amd64
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=wizeq_password
      - MYSQL_DATABASE=wizeq
      - MYSQL_TCP_PORT=3307
    ports:
      - 3307:3307
    volumes:
      - test-db:/var/lib/mysql

volumes: 
  db:
  test-db:

