version: "3.8"

services:
  postgres:
      image: ankane/pgvector
      container_name: postgres
      ports:
        - '5431:5432'
      restart: unless-stopped
      env_file: ./.env
      volumes:
        - db_data:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: wizeq_password
        POSTGRES_DB: wizeq
  integration-tests-prisma:
      image: ankane/pgvector
      container_name: integration-tests-prisma
      ports:
      - '5433:5432'
      environment:
        POSTGRES_PASSWORD: wizeq_password
        POSTGRES_DB: wizeq
      restart: unless-stopped
      env_file: ./.env
      volumes:
        - test-db:/var/lib/postgresql/data
volumes: 
  test-db:
  db_data:
