export const ACTIONS = {
  PINNIN: "pin",
  VOTE_QUESTION: 'vote_question',
  CREATE_QUESTION_ANSWER: 'create_question_answer',
  UPDATE_QUESTION_ANSWER: 'edit_question_answer',
  DELETE_ANSWER: 'delete_answer',
  ASSIGN_QUESTION: 'assign_question',
  CREATE_COMMENT: 'create_comment',
  UPDATE_COMMENT: 'update_comment',
  VOTE_COMMENT:'vote_comment',
  DELETE_COMMENT: 'delete_commet',
  APPROVED_COMMENT: 'approved_comment', 
  SCORE_ANSWER: 'score_answer',
  DELETE_SCORE: 'delete_answer_score',
};
