-- AlterTable
ALTER TABLE `Questions` MODIFY `createdAt` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    MODIFY `updatedAt` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    MODIFY `is_pinned` BOOLEAN NOT NULL DEFAULT false;
