require('dotenv').config();

module.exports = {
  ADMIN_EMAIL_TO_UNASSIGNED_QUESTION: process.env.DEFAULT_NONPROD_EMAIL_RECIPIENT,
  LOGO: 'wizeline-logo.png',
  LOGO_PATH: 'notifications/emailNotifications/templates/images',
  LAYOUT_PATH: 'notifications/emailNotifications/templates/layouts/emailNotificationLayout.html',
  VIEWS: '../views',
  TEMPLATE_NAMES: {
    YOUR_QUESTION_WAS_ANSWERED: 'question_was_answered.html',
    YOUR_ANSWER_WAS_UPDATED: 'answer_was_updated.html',
    REMINDER_TO_ANSWER_THE_QUESTION: 'reminder_to_answer_a_question.html',
    ANONYMOUS_ASKS_TO_EMPLOYEE: 'anonymous_author_ask_to_employee.html',
    ANONYMOUS_ASKS_WITHOUT_ASSIGN_QUESTION: 'anonymous_created_unassigned_question.html',
    AUTHOR_ASKS_TO_EMPLOYEE: 'author_asks_to_employee.html',
    AUTHOR_ASKS_WITHOUT_ASSIGN_QUESTION: 'author_created_unassigned_question.html',
  },
  SUBJECTS: {
    YOUR_QUESTION_WAS_ANSWERED: 'Hey there! Your question has been answered',
    YOUR_ANSWER_WAS_UPDATED: 'Hey there! Your answer has been updated',
    REMINDER_TO_ANSWER_THE_QUESTION: 'Hey there! there is a question waiting for your answer',
    ANONYMOUS_ASKS_TO_EMPLOYEE: 'You have been assigned to answer a question at WizeQ!',
    ANONYMOUS_ASKS_WITHOUT_ASSIGN_QUESTION: 'Someone has created an unassigned question',
    AUTHOR_ASKS_TO_EMPLOYEE: 'You have been assigned to answer a question at WizeQ!',
    AUTHOR_ASKS_WITHOUT_ASSIGN_QUESTION: 'has created an unassigned question',
  },
  EMAIL_FIRST_NOTIFICATION_SUBJECT: 'Hey there! someone has assigned you a question on WizeQ.',
  EMAIL_REMAINDER_NOTIFICATION_SUBJECT: 'Hey there! there is a question waiting for your answer',
  EMAIL_FIRST_NOTIFICATION: 'assigned',
  EMAIL_REMAINDER_NOTIFICATION: 'remainder',
  EMAIL_DAILY_NOTIFICATION: 'daily',
  EMAIL_NOTIFICATION_BODY: '<p>As a leader at Wizeline, a timely answer is important to our team members. Please answer the question within 48 hours. Thank you.</p>To answer the question click ',
  EMAIL_TO_ASSIGNED_ADMIN: 'email_to_assigned_admin',
  EMAIL_TO_ASSIGNER_ADMIN: 'email_to_assigner_admin',
  EMAIL_TO_ASSIGNED_ADMIN_FROM_USER: 'email_to_assigned_admin_from_user',
  EMAIL_SEE_QUESTION: 'To see the question, click ',
  EMAIL_ANSWER_QUESTION: 'To answer the question, click ',
  EMAIL_ASSIGNED_QUESTION_SUBJECT: 'You have been assigned to answer a question at WizeQ!',
  EMAIL_UNASSIGNED_QUESTION_SUBJECT: 'Someone has created an unassigned question',
  EMAIL_SIGNATURE: ' Thanks for helping us keep Wizeliners informed!<br/>Best,<br/>WizeQ Team.',
};
