steps:
  - id: 'Build Image'
    dir: '/workspace'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/wizeline-questions/wize-q-remix:$SHORT_SHA', '.' ]
  - id: 'Push Image'
    dir: '/workspace'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/wizeline-questions/wize-q-remix:$SHORT_SHA' ]
  - id: 'Validate Terraform'
    name: 'hashicorp/terraform:0.12.21'
    entrypoint: 'sh'
    dir: '/workspace/infrastructure'
    timeout: 600s
    args:
      - '-c'
      - |
        terraform init
        terraform fmt
        terraform validate
        terraform plan -var 'short_sha=$SHORT_SHA' -var-file='$_DEPLOY_ENV.tfvars'
  # - id: 'Apply Terraform'
  #   name: 'hashicorp/terraform:0.12.21'
  #   entrypoint: 'sh'
  #   dir: '/workspace/infrastructure'
  #   args:
  #     - '-c'
  #     - |
  #       terraform init
  #       terraform workspace select $_DEPLOY_ENV  || terraform workspace new $_DEPLOY_ENV 
  #       terraform apply -auto-approve -var 'short_sha=$SHORT_SHA' -var-file='$_DEPLOY_ENV.tfvars'
timeout: 1500s